[project]
name = "justice-redact-backend"
version = "0.1.0"
description = "Backend API for Justice Redact"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "python-multipart",
    "pydantic",
    "justice-redact",
]

[dependency-groups]
dev = [
    "pytest",
]

[tool.uv]
system-certs = true
package = false

[tool.uv.sources]
justice-redact = { git = "ssh://git@github.com/moj-analytical-services/justice-redact.git", rev = "62a9473880886a52e5e4a3b66f1c1299ea12b6c9" }